### ISSUE TITLE
Пазбавіцца ад формы

### ISSUE THREAD

**Issue by HaraldZealot** [BSU2013gr0209web/LatushkinDA09#1]
Другім разам можа быць мінус за невыкананне умоваў задачы. У першай лабараторнай было забаронена карыстацца формамі. 

Выпраўляйце.

**Comment by captOsmant** [comment]
Файл формы удален из репозитория.

**Comment by HaraldZealot** [comment]
І я ўчора ужо зняў з вас пытальнік
